"""Render docs/EVALUATION.md from models/mask_classifier.json (so the report can never disagree with the model)."""

from __future__ import annotations

import json
import sys
from pathlib import Path


def pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def main() -> None:
    meta = json.loads(Path(sys.argv[1] if len(sys.argv) > 1 else "models/mask_classifier.json").read_text())
    out = Path(sys.argv[2] if len(sys.argv) > 2 else "docs/EVALUATION.md")
    t, e = meta["test_metrics"], meta["end_to_end"]
    labels = meta["labels"]
    cm = t["confusion"]
    lines = [
        "# Evaluation",
        "",
        "Generated by `training/make_report.py` from `models/mask_classifier.json`. Everything below was measured on a **held-out test split of",
        f"{t['test_images']} images / {t['test_faces']} faces that were never used for training, epoch selection or calibration**. The split is by image (seed {meta['seed']}), so faces from one photo never appear on both sides.",
        "",
        f"* Dataset: `{meta['dataset']['repo']}` @ `{meta['dataset']['revision'][:12]}` (Kaggle *Face Mask Detection*, license {meta['dataset']['license']}); {meta['splits']}.",
        f"* Training faces per class ({', '.join(labels)}): {meta['train_faces_per_class']}. Model: MobileNetV3-Small, {meta['epochs']} epochs, torch {meta['torch']}.",
        "* The test set is small (and tiny for `mask_weared_incorrect`), so **every figure has wide uncertainty**; intervals are Wilson 95%.",
        "",
        "## 1. Classifier on ground-truth face boxes",
        "",
        f"**Accuracy {pct(t['accuracy'])}** (95% CI {pct(t['accuracy_ci95'][0])} to {pct(t['accuracy_ci95'][1])}); macro-F1 {t['macro_f1']:.3f}.",
        f"For scale: always answering `with_mask` would score {pct(cm[0][0] + cm[0][1] + cm[0][2] and t['per_class']['with_mask']['support'] / t['test_faces'])} on this split, so accuracy alone flatters the model.",
        "",
        "| Class | Test faces | Precision | Recall |",
        "|---|---|---|---|",
    ]
    for name in labels:
        c = t["per_class"][name]
        lines.append(f"| {name} | {c['support']} | {pct(c['precision'])} | {pct(c['recall'])} |")
    lines += [
        "",
        "Confusion matrix (rows = truth, columns = prediction):",
        "",
        "| | " + " | ".join(labels) + " |",
        "|---|" + "---|" * len(labels),
    ]
    for name, row in zip(labels, cm, strict=True):
        lines.append(f"| **{name}** | " + " | ".join(str(v) for v in row) + " |")
    lines += [
        "",
        "> **`mask_weared_incorrect` is the weak class**: only 84 training faces and 16 test faces, and the model finds "
        f"{pct(t['per_class']['mask_weared_incorrect']['recall'])} of them, most often calling them `with_mask`. Do not rely on that label.",
        "",
        "### By face size (shorter side of the box)",
        "",
        "| Face size | Test faces | Accuracy | 95% CI |",
        "|---|---|---|---|",
    ]
    for name, v in t["by_face_size"].items():
        lines.append(f"| {name} | {v['n']} | {pct(v['accuracy'])} | {pct(v['ci95'][0])} to {pct(v['ci95'][1])} |")
    lines += [
        "",
        "Small faces score *well* here, which should be read with suspicion rather than pride: in this dataset small faces come mostly from crowd photos of",
        "masked people, so the classifier may partly be learning scene context. It was not tested on unmasked crowds of small faces.",
        "",
        "### Calibration",
        "",
        f"A softmax temperature ({meta['temperature']:.2f}) was fitted on the **validation** split only and baked into the ONNX graph. Expected calibration error (15 bins): "
        f"uncalibrated {t['ece_uncalibrated']:.3f}, calibrated {t['ece_calibrated']:.3f} on the test split.",
        "The validation ECE improved after calibration but the test ECE did not, so **there is no evidence the calibration helped on unseen data**; both values are small (a few percent).",
        f"With the default `uncertain` threshold of 0.7, {pct(t['coverage_at_0.7'])} of test faces are confidently classified and {pct(t['accuracy_when_confident'])} of those are correct.",
        "",
        "## 2. End to end with the service's detector",
        "",
        "The real service first *detects* faces (YuNet, score 0.7, small images upscaled to 1024 px, the defaults), then classifies each detection. A ground-truth face counts as found when a detection overlaps it with IoU >= 0.5.",
        "",
        f"* **Faces found: {e['detected']} of {e['gt_faces']} ({pct(e['detection_recall'])})**; **{e['false_positive_detections']} false detections** ({e['false_positive_detections'] / t['test_images']:.2f} per image).",
        f"* **Label accuracy on the faces that were found: {pct(e['label_accuracy_on_detected'])}.**",
        "",
        "| Face size | Ground-truth faces | Found |",
        "|---|---|---|",
    ]
    for name, (rec, n) in e["detection_recall_by_size"].items():
        lines.append(f"| {name} | {n} | {pct(rec) if rec is not None else 'n/a'} |")
    lines += [
        "",
        "**Detection, not classification, is the practical limit.** About one face in four is missed, and two in three of the smallest ones. Anything you count from this service is a *lower bound* on the people present.",
        "",
        "Detector settings (score threshold 0.7, upscale-to 1024 px) were chosen on the *validation* images with `training/tune_detector.py`; on those, upscaling raised face recall from 57% to 78% at 0.77 false detections per image.",
        "",
        "## Reproduce",
        "",
        "See [training/README.md](../training/README.md). Training uses the Apple GPU (MPS) when available, which is not bit-for-bit deterministic, so re-running gives similar but not identical numbers.",
    ]
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
